"""
Django settings for wroclawskiewalentynki project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path


"""
To run app:
1) Create localsettings.py file in the same directory as this one
2) Set
* 'ALLOWED HOSTS' - array of server hosts,
* 'LANGUAGE_CODE' - set language of the app (currently only en-us and pl),
* 'DEBUG' - do not set this to True in deployment,
* 'SECRET_KEY' - key to secure website, use something long,
* 'EMAIL_BACKEND' - backend used to send mails (default is specified),
* 'EMAIL_HOST' - mailing server you will use,
* 'EMAIL_FROM' - email that will be shown as sender in client's mail app,
* 'EMAIL_HOST_USER' - mailing server user you'd set,
* 'EMAIL_HOST_PASSWORD' - password for mailing sever user,
* 'EMAIL_PORT' - port of your mailing server used for sending, fe. using SMTP,
* 'NOREPLY_EMAIL' - email that will send noreply messages,
* 'WWW_SITE' - site that will be displayed in every noreply message with confirmation.
* 'MAIN_CHANNEL_HOST' - redis server IP and PORT [tuple (ip, port)], default is ('127.0.0.1', 6379)
* 'ADMINS' - list of admin e-mail addresses tuples (name, email) 
"""


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
SITE_ROOT = os.path.dirname(os.path.realpath(__name__))

# SET DEBUG and SECRET_KEY in localsettings.py
DEBUG = False
SECRET_KEY = 'this-key-is-unsecure'

# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY WARNING: don't run with debug turned on in production!

# Emailing settings (set in localsettings.py)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST =
# EMAIL_FROM =
# EMAIL_HOST_USER =
# EMAIL_HOST_PASSWORD =
# EMAIL_PORT =
# NOREPLY_EMAIL =
# WWW_SITE =
EMAIL_USE_SSL = True

PASSWORD_RESET_TIMEOUT = 14400

ALLOWED_HOSTS = []

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'core',
    'chat',
    'match',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware'
]

ROOT_URLCONF = 'wroclawskiewalentynki.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'wroclawskiewalentynki.asgi.application'

MAIN_CHANNEL_HOST = ("127.0.0.1", 6379)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [MAIN_CHANNEL_HOST],
        },
    },
}

LOGIN_REDIRECT_URL = '/chat/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/login/'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR /'static'
]

LOCALE_PATHS = [
    BASE_DIR / 'locale'
]

# Where collectstatic collects static (for production)

STATIC_ROOT = BASE_DIR / 'staticfiles/'
MEDIA_ROOT = 'mediafiles/'

MAX_MESSAGE_LENGTH = 4096

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CSRF_COOKIE_SECURE = True

SESSION_COOKIE_SECURE = True

SECURE_SSL_REDIRECT = True

try:
    from .localsettings import *
except ImportError:
    print("localsettings.py not found")
