# Generated by Django 4.1.5 on 2023-01-25 20:07

import django.core.validators
from django.db import migrations, models
import match.models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_userprofile_school_alter_school_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accept_terms',
            field=models.BooleanField(default=True, verbose_name='I accept terms of use (available in the footer of the page).'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='school',
            field=models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3), match.models.validate_school], verbose_name='School code'),
        ),
    ]
