# Generated by Django 4.1.5 on 2023-01-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_userprofile_accept_terms_alter_userprofile_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='matched',
            field=models.BooleanField(default=False),
        ),
    ]
