# Generated by Django 4.1.5 on 2023-01-28 20:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_userprofile_matched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='question13',
            field=models.IntegerField(choices=[(1, 'Mathematics/Physics'), (2, 'Polish'), (3, 'Geography'), (4, 'IT'), (5, 'History/Society knowledge'), (6, 'Foreign Languages'), (7, 'Biology/Chemistry'), (8, 'PE')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='My favorite subject at school is:'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='question9',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='On a scale of 1 to 10, how decisive are you?'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match1_set', to='match.userprofile')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match2_set', to='match.userprofile')),
            ],
        ),
    ]
