# Generated by Django 4.1.5 on 2023-01-28 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_alter_userprofile_question13_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='user1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match1_set', to='match.userprofile'),
        ),
        migrations.AlterField(
            model_name='match',
            name='user2',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match2_set', to='match.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('user1', 'user2')},
        ),
    ]
