# Generated by Django 4.1.5 on 2023-02-02 18:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import match.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('match', '0010_alter_userprofile_question13'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='accept_terms',
            field=models.BooleanField(default=None, verbose_name='I accept terms of use (available in the footer of the page).'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='question1',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth')], default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='What class are you in?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='question10',
            field=models.IntegerField(choices=[(1, 'Dogs, cats are too independent'), (2, 'Cats, dogs stink'), (3, "I don't like animals"), (4, "Doesn't matter, I love all animals")], default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Dogs or perhaps cats?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='question11',
            field=models.IntegerField(choices=[(1, '1 - I plan everything, ordnung muss sein'), (2, '2'), (3, '3'), (4, '4'), (5, '5 - Full of spontaneity')], default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='How spontaneous are you?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='question12',
            field=models.IntegerField(choices=[(1, "Yes, I'd rather not bother with them"), (2, 'No, nothing that human is to me strange')], default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='Do you avoid serious topics?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='question13',
            field=models.IntegerField(choices=[(1, 'Mathematics/Physics'), (2, 'polski'), (3, 'Geography'), (4, 'IT'), (5, 'History/Society knowledge'), (6, 'Foreign Languages'), (7, 'Biology/Chemistry'), (8, 'PE')], default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='My favorite subject at school is:'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='question2',
            field=models.IntegerField(choices=[(1, 'Boy'), (2, 'Girl'), (3, 'Non-binary person')], default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='You identify yourself as:'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='question3',
            field=models.IntegerField(choices=[(1, 'Boy'), (2, 'Girl'), (3, 'Non-binary person'), (4, "I don't care")], default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Who would you like to be matched with?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='question4',
            field=models.IntegerField(choices=[(1, 'For a date 😎'), (2, 'To meet someone interesting')], default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='I want to meet:'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='question5',
            field=models.IntegerField(choices=[(1, 'Cinema'), (2, 'Museum'), (3, 'Coffee'), (4, 'Drink (or three)'), (5, 'Billards')], default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='The ideal date/meeting is:'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='question6',
            field=models.IntegerField(choices=[(1, "I'm going to a meeting"), (2, 'I go home and study for the test')], default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='You have a geo test tomorrow, but you were supposed to meet your friends today. What do you do?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='question7',
            field=models.IntegerField(choices=[(1, 'I play Fifa/LOL/CS or whatever'), (2, 'I meet with friends'), (3, 'I read'), (4, 'Sports/gym 😎💪🏋'), (5, 'I watch - movies, series')], default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='In free time:'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='question8',
            field=models.IntegerField(choices=[(1, 'Mata'), (2, 'Freddie Mercury'), (3, 'Malik Montana'), (4, 'Ludwig van BeethovenDrake'), (5, 'Frank Sinatra'), (6, 'Lana Del Rey'), (7, 'Zbigniew Wodecki'), (8, 'Red Hot Chili Peppers'), (9, 'Dawid Podsiadło'), (10, 'BTS'), (11, 'Harry Styles'), (12, 'Arctic Monkeys'), (13, 'Pleyboy Carti')], default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)], verbose_name='If you had to listen to one musician for the next year, it would be:'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='question9',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='On a scale of 1 to 10, how decisive are you?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='school',
            field=models.CharField(default=None, max_length=3, validators=[django.core.validators.MinLengthValidator(3), match.models.validate_school], verbose_name='School code'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
