# Generated by Django 4.1.5 on 2023-02-06 12:54

import django.core.validators
from django.db import migrations, models
import match.models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0011_alter_userprofile_accept_terms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='code',
            field=models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='accept_terms',
            field=models.BooleanField(default=None, verbose_name='Akceptuję Regulamin oraz Politykę prywatności.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='Link do profilu na Facebooku (nieobowiązkowe)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Link do profilu na Instagramie (nieobowiązkowe)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='question1',
            field=models.IntegerField(choices=[(1, 'Pierwsza'), (2, 'Druga'), (3, 'Trzecia'), (4, 'Czwarta')], default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='W której klasie jesteś?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='question10',
            field=models.IntegerField(choices=[(1, 'Psy, koty są zbyt niezależne'), (2, 'Koty, psy śmierdzą'), (3, 'Nie lubię zwierząt'), (4, 'Bez znaczenia, kocham wszytskie zwierzątka')], default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Psy, czy może jednak koty?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='question11',
            field=models.IntegerField(choices=[(1, '1 - Planuję wszytsko, ordnung muss sein'), (2, '2'), (3, '3'), (4, '4'), (5, '5 - Pełen spontan')], default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Jak bardzo sponataniczn* jesteś?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='question12',
            field=models.IntegerField(choices=[(1, 'Tak, wolę nie zaprzątać sobie nimi głowy'), (2, 'Nie, nic co ludzkie nie jest mi obce')], default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='Unikasz poważnych tematów?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='question13',
            field=models.IntegerField(choices=[(1, 'Matematyka/fizyka'), (2, 'Polski'), (3, 'Geografia'), (4, 'Informatyka'), (5, 'Historia lub WOS'), (6, 'Języki obce'), (7, 'Biologia/chemia'), (8, 'WF')], default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Mój ulubiony przedmiot w szkole to:'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='question2',
            field=models.IntegerField(choices=[(1, 'Chłopak'), (2, 'Dziewczyna'), (3, 'Osoba niebinarna')], default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Identyfikujesz się jako:'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='question3',
            field=models.IntegerField(choices=[(1, 'Chłopak'), (2, 'Dziewczyna'), (3, 'Osoba niebinarna'), (4, 'Nie ma to dla mnie znaczenia')], default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Do kogo chciałbyś/chciałabyś być dopasowan*?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='question4',
            field=models.IntegerField(choices=[(1, 'Na randeczkę 😎'), (2, 'Żeby poznać kogoś ciekawego')], default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='Chcę się spotkać:'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='question5',
            field=models.IntegerField(choices=[(1, 'Kino'), (2, 'Muzeum'), (3, 'Kawa'), (4, 'Drink (albo trzy)'), (5, 'Bilard')], default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Idealna randka/spotkanie to:'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='question6',
            field=models.IntegerField(choices=[(1, 'Idę na spotkanie'), (2, 'Idę do domu i uczę się na sprawdzian')], default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='Masz jutro sprawdzian z geografii, ale miał*ś się dziś spotkać ze znajomymi. Co robisz?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='question7',
            field=models.IntegerField(choices=[(1, 'Gram w Fife/Ligę/CSa lub cokolwiek innego'), (2, 'Spotykam się ze znajomymi'), (3, 'Czytam'), (4, 'Sport/siłownia mordeczko 😎💪🏋'), (5, 'Oglądam - filmy, seriale')], default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='W wolnym czasie:'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='question8',
            field=models.IntegerField(choices=[(1, 'Mata'), (2, 'Freddie Mercury'), (3, 'Malik Montana'), (4, 'Ludwig van Beethoven'), (5, 'Frank Sinatra'), (6, 'Lana Del Rey'), (7, 'Zbigniew Wodecki'), (8, 'Red Hot Chili Peppers'), (9, 'Dawid Podsiadło'), (10, 'BTS'), (11, 'Harry Styles'), (12, 'Arctic Monkeys'), (13, 'Pleyboy Carti')], default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)], verbose_name='Jeśli miałbyś/miałabyś słuchać jednego muzyka przez najbliższy rok, byłby to:'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='question9',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='W skali od 1 do 10, jak bardzo decyzyjn* jesteś?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='school',
            field=models.CharField(default=None, max_length=3, validators=[django.core.validators.MinLengthValidator(3), match.models.validate_school], verbose_name='Kod szkoły'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tiktok',
            field=models.URLField(blank=True, verbose_name='Link do profilu na TikToku (nieobowiązkowe)'),
        ),
    ]
