# Generated by Django 4.1.5 on 2023-02-06 13:02

from django.db import migrations, models
import match.models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0012_alter_school_code_alter_school_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='accept_terms',
            field=models.BooleanField(default=None, validators=[match.models.validate_accept], verbose_name='Akceptuję Regulamin oraz Politykę prywatności.'),
        ),
    ]
