# Generated by Django 4.1.6 on 2023-02-11 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0013_alter_userprofile_accept_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='question1',
            field=models.IntegerField(choices=[(1, 'Pierwszej'), (2, 'Drugiej'), (3, 'Trzeciej'), (4, 'Czwartej')], default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='W której klasie jesteś?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='question3',
            field=models.IntegerField(choices=[(1, 'Chłopak'), (2, 'Dziewczyna'), (3, 'Nie ma to dla mnie znaczenia')], default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Do kogo chciałbyś/chciałabyś być dopasowan*?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='question8',
            field=models.IntegerField(choices=[(1, 'Mata'), (2, 'Freddie Mercury'), (3, 'Malik Montana'), (4, 'Ludwig van Beethoven'), (5, 'Frank Sinatra'), (6, 'Lana Del Rey'), (7, 'Zbigniew Wodecki'), (8, 'Red Hot Chili Peppers'), (9, 'Dawid Podsiadło'), (10, 'BTS'), (11, 'Harry Styles'), (12, 'Arctic Monkeys'), (13, 'Pleyboi Carti')], default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)], verbose_name='Jeśli miałbyś/miałabyś słuchać jednego muzyka przez najbliższy rok, byłby to:'),
        ),
    ]
