# Generated by Django 4.1.6 on 2023-02-12 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('match', '0014_alter_userprofile_question1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='matched_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chat.thread'),
        ),
    ]
