# Generated by Django 4.1.6 on 2023-02-13 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0015_match_matched_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='exact',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='question8',
            field=models.IntegerField(choices=[(1, 'Mata'), (2, 'Freddie Mercury'), (3, 'Malik Montana'), (4, 'Ludwig van Beethoven'), (5, 'Frank Sinatra'), (6, 'Lana Del Rey'), (7, 'Zbigniew Wodecki'), (8, 'Red Hot Chili Peppers'), (9, 'Dawid Podsiadło'), (10, 'BTS'), (11, 'Harry Styles'), (12, 'Arctic Monkeys'), (13, 'Playboi Carti')], default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)], verbose_name='Jeśli miałbyś/miałabyś słuchać jednego muzyka przez najbliższy rok, byłby to:'),
        ),
    ]
